import type { Route } from "./types";

// The doc's own Route 104 example: Oak Elementary morning pickup, Bus 37,
// driver John Smith. Swap this for real routing/stop data later.
export const sampleRoute: Route = {
  name: "Oak Elementary — Morning Pickup",
  routeNumber: "104",
  driverName: "John Smith",
  busNumber: "37",
  departureTime: "7:12 AM",
  steps: [
    {
      id: 0,
      kind: "depart",
      heading: "START ROUTE 104",
      subheading: "Oak Elementary — Morning Pickup",
      distance: "Bus 37 · Driver John Smith · 7:12 AM departure",
      announcement:
        "Starting Route 104. Oak Elementary, morning pickup. Bus 37, driver John Smith.",
    },
    {
      id: 1,
      kind: "turn",
      heading: "TURN RIGHT",
      subheading: "Oak Street",
      distance: "500 ft ahead",
      announcement:
        "Turn right onto Oak Street. Your next stop is 142 Oak Street, approximately one minute ahead.",
    },
    {
      id: 2,
      kind: "stop",
      subheading: "142 Oak Street",
      studentCount: 2,
      pickupOrDropoff: "Pickup",
      sideOfRoad: "right",
      specialInstruction: "Parent requests curbside pickup.",
      announcement: "Stop ahead. Two students. Pickup on right side.",
    },
    {
      id: 3,
      kind: "turn",
      heading: "CONTINUE STRAIGHT",
      subheading: "Oak Avenue",
      distance: "0.4 mi",
      announcement: "Continue straight on Oak Avenue for four tenths of a mile.",
    },
    {
      id: 4,
      kind: "stop",
      subheading: "217 Oak Avenue",
      studentCount: 1,
      pickupOrDropoff: "Pickup",
      sideOfRoad: "left",
      announcement: "Stop ahead. One student. Pickup on left side.",
    },
    {
      id: 5,
      kind: "turn",
      heading: "TURN LEFT",
      subheading: "Franklin Road",
      distance: "800 ft ahead",
      announcement: "In 800 feet, turn left onto Franklin Road.",
    },
    {
      id: 6,
      kind: "stop",
      subheading: "118 Franklin Road",
      studentCount: 3,
      pickupOrDropoff: "Pickup",
      sideOfRoad: "right",
      specialInstruction: "Wheelchair lift required.",
      announcement: "Stop 14. Three students. Pickup. Wheelchair lift required.",
    },
    {
      id: 7,
      kind: "turn",
      heading: "CONTINUE",
      subheading: "Franklin Road",
      distance: "0.6 mi",
      announcement: "Next stop, 225 Franklin Road, two students.",
    },
    {
      id: 8,
      kind: "stop",
      subheading: "225 Franklin Road",
      studentCount: 2,
      pickupOrDropoff: "Pickup",
      sideOfRoad: "right",
      announcement: "Stop ahead. Two students. Pickup on right side.",
    },
    {
      id: 9,
      kind: "arrive",
      heading: "ARRIVE AT SCHOOL",
      subheading: "Oak Elementary",
      announcement: "Arriving at Oak Elementary. Drop off all students.",
    },
  ],
};
